### ISSUE TITLE
renegade code review

### ISSUE THREAD

**Issue by shrugs** [Shikkic/gh-scrape#1]
[requiring underscore and not using it?](https://github.com/Shikkic/gh-scrape/blob/master/index.js#L2) Don't forget to remove it from [package.json](https://github.com/Shikkic/gh-scrape/blob/master/package.json#L14)

Does the `scrapeContributionData` function have a bug in it on [this line](https://github.com/Shikkic/gh-scrape/blob/master/index.js#L8)? the `data` variable doesn't exist in this scope. should `data` be `html` instead? Maybe I'm missing something, but it doesn't look like `scrapeContributionData` will ever work correctly.

Your separation of concerns for each function is :+1: 

Should `return Error;` on [this line](https://github.com/Shikkic/gh-scrape/blob/master/index.js#L113) be `return error;`, to re-use the request's error, instead of returning the `Error` class?

**Comment by Shikkic** [comment]
I think the underscore was used for a previous build, I think I was going to use it for some cleaner iterative functions for pulling out most recent commit data. 

Oh my, I didn't even notice that, I have been using this module for bitBar and have seen this error. I thought it was a connectivity issue. However I can still get it to work sometimes, so thats weird...

Ahh that last bit also makes sense as well.

**Comment by Shikkic** [comment]
I don't like the error handling I have for this. It will at most check twice. I haven't really found module that allows to request and retry based on a condition of the value. Any thoughts?
